[build]
  publish = "dist"
  command = "npm run build"

# Redirection des anciennes URLs vers la page d'authentification
[[redirects]]
  from = "/src/overlays/*"
  to = "/src/auth.html"
  status = 301
  force = true

# Redirection des accès directs aux assets vers la page d'authentification
[[redirects]]
  from = "/src/images/*"
  to = "/src/auth.html"
  status = 301
  force = false
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/src/styles/*"
  to = "/src/auth.html"
  status = 301
  force = false
  conditions = {Role = ["anonymous"]}

# Redirection des accès directs aux fichiers JS vers la page d'authentification
[[redirects]]
  from = "/src/js/*"
  to = "/src/auth.html"
  status = 301
  force = false
  conditions = {Role = ["anonymous"]}

# Redirection par défaut pour les routes non trouvées
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité pour tous les fichiers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; frame-ancestors 'self'"