[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/auth/google-callback.html"
  to = "/auth/google-callback.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 