[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/src/auth/callback/*"
  to = "/src/auth/callback/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"